### ISSUE TITLE
Indicate `voting status`, who has voted and who hasn't.

### ISSUE THREAD

**Issue by shobhitg** [PDarrall/secret-hitler#5]
There is often confusion and disarray when the game gets stuck on an AFK user.

But its possible that this messes up with the meta. Sometimes players don't want to look like that they haven't made up their mind.

But if as per the rules, voting status (not result) is not anonymous, then we should show the status. 

Else we should close this issue.

**Comment by PDarrall** [comment]
If we do implement this one it needs to be an option selected as part of the game setup. There is a considerable backlash against this feature.

**Comment by PDarrall** [comment]
#49 Being implemented
